### ISSUE TITLE
product images and descriptions

### ISSUE THREAD

**Issue by dofelton** [Juarpla/handcrafted-haven#52]

**Comment by leoaam24** [comment]
[
  {
    "name": "Wooden Sculpture",
    "image_url": "https://example.com/images/wooden_sculpture.jpg",
    "price": 40.00,
    "stock": 5,
    "description": "This beautifully carved wooden sculpture was crafted by a local artist who finds inspiration in the natural curves and textures of the wood. Each piece is meticulously shaped by hand, with attention to detail that brings the wood to life. Displayed on a shelf or table, this sculpture adds a touch of rustic elegance to any space."
  },
  {
    "name": "Handwoven Basket",
    "image_url": "https://example.com/images/handwoven_basket.jpg",
    "price": 35.00,
    "stock": 8,
    "description": "Woven with care by a skilled artisan, this sturdy and elegant handwoven basket is the result of a centuries-old tradition. Crafted from natural fibers, each basket is one-of-a-kind, with a unique pattern and texture that reflects the maker's touch. Use it for storage, display, or as a decorative piece to bring warmth and character to your home."
  },
  {
    "name": "Ceramic Vase",
    "image_url": "https://example.com/images/ceramic_vase.jpg",
    "price": 50.00,
    "stock": 3,
    "description": "This hand-thrown ceramic vase is a true work of art. The potter, a local craftsman with a passion for ceramics, carefully shapes each piece on a pottery wheel, then applies a unique glaze that transforms the surface into a mesmerizing play of colors and textures. Whether you fill it with fresh flowers or display it on its own, this vase will add a touch of artistry and visual interest to any room."
  },
  {
    "name": "Macramé Wall Hanging",
    "image_url": "https://example.com/images/macrame_wall_hanging.jpg",
    "price": 65.00,
    "stock": 4,
    "description": "Crafted with an eye for detail and a love of traditional techniques, this intricate macramé wall hanging brings a warm, bohemian touch to any space. The maker, a fiber artist who learned the craft from her grandmother, has woven natural cotton cords into a mesmerizing pattern that dances with the light. Hang this piece in your living room, bedroom, or entryway to add texture, depth, and a touch of handmade charm."
  },
  {
    "name": "Hand-Painted Silk Scarf",
    "image_url": "https://example.com/images/silk_scarf.jpg",
    "price": 80.00,
    "stock": 6,
    "description": "This luxurious hand-painted silk scarf is a true work of wearable art. The artist, who draws inspiration from the natural world, carefully applies vibrant dyes to the smooth silk surface, creating a one-of-a-kind design that flows and shifts with the movement of the fabric. Wrap this scarf around your neck, tie it to your handbag, or frame it as a piece of wall art - however you choose to display it, this scarf is sure to be a conversation starter."
  },
  {
    "name": "Stained Glass Suncatcher",
    "image_url": "https://example.com/images/stained_glass_suncatcher.jpg",
    "price": 45.00,
    "stock": 7,
    "description": "Handcrafted by a local artisan with a passion for the ancient art of stained glass, this colorful suncatcher will brighten any window it graces. Each piece is carefully assembled from carefully selected pieces of colored glass, which are then soldered together to create a dazzling design. Hang this suncatcher in a sunny spot and watch as the light filters through, casting a kaleidoscope of colors on the walls around it."
  },
  {
    "name": "Leather Journal",
    "image_url": "https://example.com/images/leather_journal.jpg",
    "price": 30.00,
    "stock": 10,
    "description": "This handbound leather journal is the perfect companion for the creative mind. Crafted by a local bookbinder with years of experience, each journal is made with high-quality paper and bound in supple, vegetable-tanned leather. Whether you use it for sketching, writing, or simply as a place to collect your thoughts, this journal will only grow more beautiful with time and use. A thoughtful gift or a treasured personal item, this journal is sure to inspire."
  },
  {
    "name": "Felted Wool Animal",
    "image_url": "https://example.com/images/felted_wool_animal.jpg",
    "price": 25.00,
    "stock": 12,
    "description": "These adorable felted wool animal figurines are the result of a painstaking process, lovingly crafted by a local artisan with a keen eye for detail and a passion for needle felting. Using only natural wool fibers, the maker carefully sculpts each creature, giving them a unique personality and charm. Display these delightful little companions on a shelf, desk, or windowsill to bring a touch of whimsy and handmade warmth to your home."
  },
  {
    "name": "Handmade Soap Set",
    "image_url": "https://example.com/images/handmade_soap_set.jpg",
    "price": 20.00,
    "stock": 15,
    "description": "Treat your senses to the luxurious experience of these artisanal handmade soaps. Crafted by a local soapmaker using natural ingredients like shea butter, essential oils, and botanical extracts, each bar is a unique work of art. Lather up and enjoy the gentle cleansing and moisturizing properties of these beautifully scented soaps, perfect for pampering yourself or gifting to a loved one."
  },
  {
    "name": "Quilted Table Runner",
    "image_url": "https://example.com/images/quilted_table_runner.jpg",
    "price": 55.00,
    "stock": 4,
    "description": "This handcrafted quilted table runner is the result of countless hours of meticulous work by a local textile artist. Drawing inspiration from the rich history of quilting, she has meticulously pieced together a patchwork of fabrics, creating a design that is both visually stunning and imbued with a sense of tradition. Whether draped across your dining table, sideboard, or accent chest, this runner will add a cozy, homespun touch to any space."
  },
  {
    "name": "Blown Glass Ornament",
    "image_url": "https://example.com/images/blown_glass_ornament.jpg",
    "price": 35.00,
    "stock": 8,
    "description": "These delicate hand-blown glass ornaments are the work of a talented local artisan who has honed her craft over many years. Using traditional glassblowing techniques, she skillfully shapes and manipulates the molten glass, infusing each piece with swirls of color that dance and refract the light. Hang these ornaments on your Christmas tree, or display them year-round as beautiful suncatchers that will bring a touch of artistry and wonder to any room."
  },
  {
    "name": "Embroidered Pillow Cover",
    "image_url": "https://example.com/images/embroidered_pillow_cover.jpg",
    "price": 40.00,
    "stock": 6,
    "description": "This exquisite hand-embroidered pillow cover is a testament to the artistry and skill of local artisans. Crafted with intricate needlework, the pillow features a traditional ethnic design that adds a touch of culture and warmth to any space. The rich colors and intricate patterns are sure to be a conversation starter."
  },
  {
    "name": "Wire-Wrapped Gemstone Pendant",
    "image_url": "https://example.com/images/wire_wrapped_pendant.jpg",
    "price": 45.00,
    "stock": 9,
    "description": "This unique wire-wrapped pendant features a natural gemstone that has been carefully selected and incorporated into a one-of-a-kind design. The maker, a skilled jeweler with a passion for working with wire and stones, has wrapped each piece by hand, creating a delicate and intricate framework that showcases the beauty of the gemstone. Wear this pendant as a statement piece or give it as a thoughtful gift to someone special - either way, it's sure to be admired for its artistry and craftsmanship."
  },
  {
    "name": "Carved Wooden Spoon Set",
    "image_url": "https://example.com/images/wooden_spoon_set.jpg",
    "price": 30.00,
    "stock": 7,
    "description": "These hand-carved wooden spoons are not only functional kitchen tools but also beautiful works of art. Crafted by a local woodworker with an eye for detail, each spoon is shaped and sculpted from a single piece of sustainably sourced wood, resulting in a unique grain pattern and organic form. Use them for stirring, serving, or simply display them as decorative accents in your kitchen - these spoons are sure to become cherished, heirloom-quality pieces in your home."
  },
  {
    "name": "Pressed Flower Art Frame",
    "image_url": "https://example.com/images/pressed_flower_art.jpg",
    "price": 60.00,
    "stock": 5,
    "description": "This framed artwork featuring delicately pressed flowers is a true testament to the beauty of nature and the skill of the artist who created it. Using a meticulous process of selecting, arranging, and preserving the flowers, the maker has crafted a piece that is both visually stunning and deeply meaningful. Hang this framed artwork in your living room, bedroom, or office to bring a touch of natural elegance and serenity to your space, and to serve as a constant reminder of the wonder that can be found in the world around us."
  }
]
